name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Build C# Code
      run: dotnet build
    
    - name: Run C# Tests
      run: dotnet test
    
    - name: Run npm tests
      working-directory: DotnetTemplate.Web
      run: npm t
      
    - name: Run npm lint test
      working-directory: DotnetTemplate.Web
      run: npm run lint